# Generated by Django 3.0.5 on 2021-05-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_dischargerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assdoc_to_Doctor_Messages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('patientId', models.PositiveIntegerField(null=True)),
                ('doctorId', models.PositiveIntegerField(null=True)),
                ('assdoctorId', models.PositiveIntegerField(null=True)),
                ('lab_report', models.ImageField(blank=True, null=True, upload_to='Lab_reports/')),
                ('assdoc_name', models.CharField(max_length=255)),
                ('doc_name', models.CharField(max_length=255)),
                ('Patient_name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
