# Generated by Django 3.1.6 on 2021-05-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_doc_to_assdoc_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assdoctor',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/AssDoctorProfilePic/'),
        ),
    ]
