# Generated by Django 3.1.1 on 2021-05-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0012_auto_20210526_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='admitrequest',
            name='assignedassDoctorId',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='admitrequest',
            name='patientId',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='assignedassDoctorId',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
