# Generated by Django 3.0.5 on 2021-05-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0013_auto_20210526_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_Bill_Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_name', models.CharField(max_length=255)),
                ('Transaction_id', models.PositiveIntegerField(null=True)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('patientId', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
