# Generated by Django 3.1.1 on 2021-05-28 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0013_auto_20210526_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admitrequest',
            name='assignedassDoctorId',
        ),
        migrations.RemoveField(
            model_name='admitrequest',
            name='patientId',
        ),
    ]
