# Generated by Django 3.0.5 on 2021-05-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0014_patient_bill_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_bill_messages',
            name='Transaction_id',
            field=models.TextField(),
        ),
    ]
