# Generated by Django 3.0.5 on 2021-05-28 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0016_auto_20210528_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient_bill_messages',
            old_name='Transaction_id',
            new_name='Transaction_Id',
        ),
    ]
