# Generated by Django 3.0.5 on 2021-05-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0017_auto_20210528_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_bill_messages',
            name='Transaction_Id',
            field=models.TextField(default='hghgv33', null=True),
        ),
    ]
