# Generated by Django 3.0.5 on 2021-05-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_auto_20210528_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_bill_messages',
            name='Transaction_Id',
            field=models.CharField(max_length=255),
        ),
    ]
