# Generated by Django 3.0.5 on 2021-05-28 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_auto_20210528_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient_bill_messages',
            old_name='patientId',
            new_name='Patient_Id',
        ),
    ]
