# Generated by Django 3.1.1 on 2021-05-28 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0014_auto_20210528_1258'),
        ('hospital', '0021_remove_patient_bill_messages_patient_id'),
    ]

    operations = [
    ]
