# Generated by Django 3.1.6 on 2021-06-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0023_auto_20210604_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assdoc_to_doctor_messages',
            name='assdoctorId',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assdoc_to_doctor_messages',
            name='doc_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
