# Generated by Django 3.1.6 on 2021-06-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0024_auto_20210606_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc_to_assdoc_messages',
            name='assdoc_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
