# Generated by Django 3.1.1 on 2021-06-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0025_auto_20210606_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assdoc_to_doctor_messages',
            name='lab_report',
            field=models.FileField(blank=True, null=True, upload_to='Lab_reports/Assdoc_to_Doctor/'),
        ),
        migrations.AlterField(
            model_name='doc_to_assdoc_messages',
            name='lab_report',
            field=models.FileField(blank=True, null=True, upload_to='Lab_reports/doc_to_Assdoc/'),
        ),
    ]
