# Generated by Django 3.1.1 on 2021-06-14 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0026_auto_20210613_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assdoc_to_doctor_messages',
            name='lab_report',
            field=models.ImageField(blank=True, null=True, upload_to='Lab_reports/Assdoc_to_Doctor/'),
        ),
        migrations.AlterField(
            model_name='doc_to_assdoc_messages',
            name='lab_report',
            field=models.ImageField(blank=True, null=True, upload_to='Lab_reports/doc_to_Assdoc/'),
        ),
    ]
